# Generated by Django 5.0.4 on 2024-04-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0003_remove_creditcard_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cleaners',
            field=models.ManyToManyField(related_name='bookings', to='keeper.cleaner'),
        ),
        migrations.DeleteModel(
            name='CleanerBooking',
        ),
    ]
